apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: basic-ingres
# uncomment if you have statis IP  
#  annotations:
#    kubernetes.io/ingress.global-static-ip-name: helloweb-ip
  
spec:
  backend:
    serviceName: frontend
    servicePort: 5000


# helper
# https://cloud.google.com/kubernetes-engine/docs/tutorials/configuring-domain-name-static-ip